name: liteRanks
version: '1.0'
main: com.crystalcraft.literanks.Main
api-version: 1.19

permissions:
  ranks:
    default: op
  #test: # debug permission used during development
  #  default: false

commands:
  ranks:
    description: main ranks command
  #ping: # debug command used during development
  #  description: debug command
  #test: # debug command used during development
  #  permission: test