name: liteRanks
version: '1.0'
main: com.crystalcraft.literanks.Main
api-version: 1.19

permissions:
  ranks:
    default: op
  test:
    default: false

commands:
  ranks:
    description: main ranks command
  ping:
    description: debug command
  test:
    permission: test